<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fake  = Faker\Factory::create();
        $description = 'Thiết kế với nhiều đột phá
        Về kích thước, iPhone 13 sẽ có 4 phiên bản khác nhau và kích thước không đổi so với series iPhone 12 hiện tại.
        Nếu iPhone 12 có sự thay đổi trong thiết kế từ góc cạnh bo tròn (Thiết kế được duy trì từ thời iPhone 6 đến iPhone 11 Pro Max) sang thiết kế vuông vắn (đã từng có mặt trên iPhone 4 đến iPhone 5S, SE).
        Thì trên điện thoại iPhone 13 vẫn được duy trì một thiết kế tương tự.
        Máy vẫn có phiên bản khung viền thép, một số phiên bản khung nhôm cùng mặt lưng kính.
        Tương tự năm ngoái, Apple cũng sẽ cho ra mắt 4 phiên bản là iPhone 13, 13 mini, 13 Pro và 13 Pro Max.';
        $image = $fake->imageUrl($width = 255.5, $height = 255.5);
        DB::table('tbl_product') -> insert([
            array(
                'brand_id' => '44',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '44',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '44',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '44',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '44',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '45',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '45',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '45',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '45',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '45',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '46',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '46',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '46',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '46',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '46',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '47',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '47',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '47',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '47',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '47',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '48',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '48',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '48',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '48',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '48',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '49',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '49',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '49',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '49',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0',
            ),
            array(
                'brand_id' => '49',
                'name' => 'iPhone 13',
                'description' => $description,
                'image' => $image,
                'price' => '42990000',
                'sale_price' => '41990000',
                'rom' => '512GB',
                'ram' => '32GB',
                'battery' => '5000mAh',
                'screen' => 'SUPER AMOLED',
                'front_camera' => '12MP, f/2.2',
                'rear_camera' => 'Camera góc rộng: 12MP, f/1.6
                Camera góc siêu rộng: 12MP, ƒ/2.4',
                'chipset' => 'Apple A15',
                'status' => '0'
            )
        ]);
    }
}
